# Generated by Django 3.2.3 on 2021-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTable1108',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_1108',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable1201',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_1201',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable1234',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_1234',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable1604',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_1604',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable2886',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_2886',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable2887',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_2887',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable2890',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_2890',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable2892',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_2892',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable3045',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_3045',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable5876',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('transaction_list', models.IntegerField(blank=True, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_table_5876',
                'managed': False,
            },
        ),
    ]
